name: build

on:
  push:
    # auto-update branches checked by created PR
    branches-ignore:
      - 'update/*'
    paths-ignore:
      - '.changeset/**'

  # only test check PR to master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: node18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: |
          npm i

      - name: typecheck
        run: |
          npm run typecheck

      - name: build
        run: |
          npm run build

  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: node18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: |
          npm -v
          npm i

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          # this step should build library with new version
          publish: npm run release
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}